### ISSUE TITLE
IntelSiliconPkg: ReportCpuHobLib fails to build (Bugzilla Bug 3404)

### ISSUE THREAD

**Issue by tianocore-issues** [tianocore/edk2-platforms#464]
This issue was created automatically with [bugzilla2github](https://github.com/makubacki/bugzilla2github/tree/bz2gh_tianocore)
# Bugzilla Bug 3404
Date: 2021-05-19T00:11:22+00:00
From: @makubacki
To:   @makubacki
CC:   

Last updated: 2021-06-22T18:29:02+00:00

**Comment by tianocore-issues** [comment]
## Comment 16097
Date: 2021-05-19 00:11:22 +0000
From: @makubacki

- Industry Specification: ---
- Release Observed: EDK II Master
- Releases to Fix: EDK II Master
- Target OS: ---
- Bugzilla Assignee(s): @makubacki

The following build error is encountered with VS2015 (and potentially other versions):

IntelSiliconPkg\Library\ReportCpuHobLib\ReportCpuHobLib.c(30):
  error C2220: warning treated as error - no &apos;object&apos; file generated
IntelSiliconPkg\Library\ReportCpuHobLib\ReportCpuHobLib.c(30):
  warning C4244: &apos;=&apos;: conversion from &apos;UINT32&apos; to &apos;UINT8&apos;,
  possible loss of data

This is a common issue related to implicitly truncating data during assignment from a larger data type to a smaller data type.

Introduced in commit d3c10d3.

**Comment by tianocore-issues** [comment]
## Comment 16098
Date: 2021-05-19 00:16:28 +0000
From: @makubacki

I will send a patch.

**Comment by tianocore-issues** [comment]
## Comment 16099
Date: 2021-05-19 00:16:39 +0000
From: @makubacki

V1 patch on mailing list: https://edk2.groups.io/g/devel/message/75342

**Comment by tianocore-issues** [comment]
## Comment 16422
Date: 2021-06-22 18:28:25 +0000
From: @makubacki

Patch was merged to edk2-platforms/master: https://github.com/tianocore/edk2-platforms/commit/e89f5830bdd19c73a99d745b2646f4821069fc76

**Comment by tianocore-issues** [comment]
## Comment 16423
Date: 2021-06-22 18:29:02 +0000
From: @makubacki

Marking as resolved
